# GET http://localhost:8001/users/show?username="test"
# Content-Type: application/json

#Cookie: XDEBUG_SESSION=start


#GET http://localhost:8001/users/show?username=testUserStasd


#POST http://localhost:8001/posts/create
#Content-Type: application/json

#{
#    "author_uuid": "8b1e3d16-023d-41d5-b9e6-87c3b89278d",
#    "text": "sss",
#    "title": "fbxff"
#}


# POST http://localhost:8001/posts/comment
#
# {
#     "post_uuid": "fedd632c-ef1a-4ccc-b2ce-4b6500d73dc9",
#     "author_uuid": "98a342bb-877c-432f-88b1-8f864ffc37f1",
#     "text": "Test Comment!",
# }

# POST http://localhost:8001/users/create

# {
#     "username":"friday",
#     "first_name":"TVadim",
#     "second_name":"Robot"
# }

#POST HTTP://localhost:8001/posts/fav
#
#{
#    "author_uuid":"4469d573-f851-4b93-a7a1-b1d43fd235ea",
#    "post_uuid":"715a1b0a-a64b-477d-8c48-b97af81e2380"
#}
// DELETE HTTP://localhost:8001/posts?uuid=311c3a97-8d6f-4334-b0e1-3d01362cdb12

#POST http://localhost:8001/posts/create
#Content-Type: application/json
#
#{
#"username": "test4",
#"password": "234",
#"text": "some text",
#"title": "some title"
#}

#POST http://localhost:8001/login
#Content-Type: application/json
#
#{
#"username": "Bot1",
#"password": "234"
#}

POST http://localhost:8001/posts/create
Authorization: Bearer 3e269c2218a193b08a324281504798fcd72cdb2b29451c243af0464d6109beef60fb6de3c59602eb

{
"text": "sss!!",
"title": "fbxff"
}


